linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - golint
    - ifshort
    - interfacer
    - lll
    - maligned
    - nosnakecase
    - paralleltest
    - scopelint
    - structcheck
    - testpackage
    - varcheck
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - varnamelen
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/wakeful/yaml2json/pkg/parse
